---
- name: Create conf folder to put nginx folder
  ansible.builtin.file:
    path: "{{ docker_base_volume_path }}/nginx/conf"
    state: directory
    mode: "0755"

- name: Copy nginx.conf to server
  template:
    src: "{{ playbook_dir }}/templates/nginx.j2"
    dest: "{{ docker_base_volume_path }}/nginx/conf/nginx.conf"

- name: Pull Nginx image
  docker_image:
    name: "nginx:{{ nginx_docker_tag }}"
    source: pull

- name: Start Nginx Container
  docker_container:
    name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: "{{ docker_network_name }}"
    hostname: "{{ docker_nginx_hostname }}"
    volumes:
      - "{{ docker_base_volume_path }}/wordpress:/var/www/html"
      - "{{ docker_base_volume_path }}/nginx/conf:/etc/nginx/conf.d"
      - "{{ docker_base_volume_path }}/nginx/logs:/var/log/nginx"
    restart: true
