---
- name: Create conf folder to put nginx folder
  ansible.builtin.file:
    path: "{{ docker_base_volume_path }}/nginx/conf"
    state: directory
    mode: "0755"

- name: Copy nginx.conf to server
  template:
    src: "{{ playbook_dir }}/templates/nginx.j2"
    dest: "{{ docker_base_volume_path }}/nginx/conf/nginx.conf"

- name: Pull Nginx image
  docker_image:
    name: "nginx:{{ nginx_docker_tag }}"
    source: pull

- include_tasks: nginx_http.yml
  when: ssl is false

- include_tasks: nginx_https.yml
  when: ssl is true
