---
- hosts: all
  collections:
    - chrissayon.wordpress_docker

  roles:
    - geerlingguy.docker
    - chrissayon.wordpress_docker.network
    - chrissayon.wordpress_docker.mysql
    - chrissayon.wordpress_docker.wordpress
    - chrissayon.wordpress_docker.nginx
