---
galaxy_info:
  author: chrissayon
  description: Pull down WordPress image and run the container
  license: MIT
  min_ansible_version: 2.1
  galaxy_tags:
    - wordpress
    - docker

dependencies: []
