---
namespace: chrissayon
name: wordpress_docker
version: "1.0.2"
readme: README.md

authors:
  - chrissayon

description: Dockerized deployment of wordpress, nginx, mysql inside docker

license:
  - MIT

tags:
  - wordpress
  - nginx
  - mysql
  - docker

dependencies:
  community.docker: "3.4.11"

repository: https://github.com/chrissayon/ansible-collection-wordpress-nginx-docker
documentation: https://github.com/chrissayon/ansible-collection-wordpress-nginx-docker
homepage: https://github.com/chrissayon/ansible-collection-wordpress-nginx-docker
issues: https://github.com/chrissayon/ansible-collection-wordpress-nginx-docker/issues

build_ignore:
  - "*.tar.gz"
  - ".github"
