---
namespace: chrissayon
name: wordpress_docker
version: "1.0.1"
readme: README.md

authors:
  - chrissayon

description: Dockerized deployment of wordpress, nginx, mysql inside docker

license:
  - MIT

tags:
  - wordpress
  - nginx
  - mysql
  - docker

dependencies:
  community.docker: "3.4.11"

repository: https://github.com/chrissayon/ansible_collection_wordpress_nginx_docker
documentation: https://github.com/chrissayon/ansible_collection_wordpress_nginx_docker
homepage: https://github.com/chrissayon/ansible_collection_wordpress_nginx_docker
issues: https://github.com/chrissayon/ansible_collection_wordpress_nginx_docker/issues

build_ignore:
  - "*.tar.gz"
