---
docker_wordpress_hostname: wordpress_host
docker_nginx_hostname: nginx_host
docker_base_volume_path: /home/wordpress_docker
docker_network_name: wordpress_network

nginx_server_name: default_server
