---
- name: Pull Wordpress image
  docker_image:
    name: wordpress:latest
    source: pull

- name: Create container with Wordpress image
  docker_container:
    name: wordpress
    image: wordpress
    networks:
      - name: "{{ docker_network_name }}"
    hostname: wordpress
    env:
      WORDPRESS_DB_HOST: "{{ db_host }}"
      WORDPRESS_DB_NAME: "{{ db_name }}"
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"
    volumes:
      - "{{ docker_base_volume_path }}/wordpress:/var/www/html"
    restart: true
