---
- name: Pull mysql image
  docker_image:
    name: "mysql:{{ mysql_docker_tag }}"
    source: pull

- name: Create container with mysql image
  docker_container:
    name: mysql
    image: mysql
    networks:
      - name: "{{ docker_network_name }}"
    hostname: "{{ docker_mysql_hostname }}"
    env:
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
